name: Deploy CI
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: install
        run: npm install

      - name: plugins
        run: yarn add umi-plugin-antd-theme umi-plugin-pro

      - name: site
        run: npm run site

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        env:
          github_token: ${{ secrets.ACTION_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./dist
        with:
          emptyCommits: false
