name: Deploy to GitHub Pages
on: [push]
jobs:
  Deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    if: success() && github.event == 'push' && github.ref == 'master'
    steps:
      - name: publish
        uses: maxheld83/ghpages@v0.2.1
        env:
          BUILD_DIR: 'dist/'
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
