name: Add an issue reference
on: [pull_request]

jobs:
  reference:
    name: reference
    uses: kentaro-m/add-an-issue-reference-action@v1.0.0
    env:
      GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
